[package]
name = "crawx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
reqwest = "0.13.1"
resext = "0.6.2"
scraper = "0.25.0"
tokio = { version = "1.49.0", features = ["full"] }
url = "2.5.8"
