[package]
name = "crawn"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
owo-colors = "4.2.3"
reqwest = "0.13.1"
resext = "0.7.0"
scraper = "0.25.0"
tokio = { version = "1.49.0", features = ["full"] }
url = "2.5.8"
